### PR TITLE
Styling/navbar color

### LINKED ISSUE #38: BUG: NavBar icon colors
**Describe the bug**

- the NavBar icons are visibly activating when they are clicked but not deactivating when we leave the page

**To Reproduce**
1. Go to `/`
2. Click on any icon in the `NavBar` 
3. notice that the color has changed on the icon that you clicked 
4. refresh
5. see that the icon has lost it's color but is still on the page that it links to
6. return to the `Dashboard` 
7. see that the icon keeps the its color 

**Expected behavior**

- should stay visibly active after refresh
- should not stay visibly active when navigating to a different page

### PR DESCRIPTION
**Pull request by richardltyler**
## *Purpose:*
*What does this merge do? Check all that apply.*
- [ ] Adds a new feature
- [ ] Improves an existing feature
- [x] Fixes a bug
- [ ] Cleans up (logs, tests, etc.)

## *Description: What does this PR do?*
*Briefly, but clearly describe what you did, and explain any new code.*
- changes the `Router` `Link` elements in the `NavBar` to `NavLink` elements
- fixes a bug where the icons in the `NavBar` icons stay visibly active when they are not supposed to 

## *Instructions for reviewer:*
*Where should the reviewer start?*
*How should this be manually tested?*
*Any background context you want to provide?*
*What are the relevant tickets?*
- closes #38 

## *Issues:*
*Are there any concerns, issues, or bugs in this branch? If so describe them.*

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have used tests to prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change

### CODE REVIEW

**Review by kevinhartmann23 — APPROVED** [review]
Nice catch, NavLink is the waaaay to go!

File: src/components/navbar/NavBar.js [hunk 1]
```diff
@@ -1,44 +1,27 @@
...
-  const [calendarButton, selectCalendar] = useState('')
-  const [addEventButton, selectAddEvent] = useState('')
-  const [contactsButton, selectContacts] = useState('')
-  
-  const toggleButtons = (active, inactive1, inactive2) => {
-    active('active')
-    inactive1('')
-    inactive2('')
-  }
-
```
Comment (DrewBradley) [inline src/components/navbar/NavBar.js:18]: SO Fresh. SO clean.

**Review by DrewBradley — APPROVED** [review]
My bad.

**Review by kristenmb — APPROVED** [review]
